// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ24O4bVBqexlDXD8IN3ATmeSHvMxBCHI',
    appId: '1:481479762043:web:57ed447e6fd790eda502de',
    messagingSenderId: '481479762043',
    projectId: 'taskflowdi2',
    authDomain: 'taskflowdi2.firebaseapp.com',
    storageBucket: 'taskflowdi2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl1mDs0SVxEcwNvD2eVNmPF2HXNYH-gPo',
    appId: '1:481479762043:android:a5ae8c0a97e39f04a502de',
    messagingSenderId: '481479762043',
    projectId: 'taskflowdi2',
    storageBucket: 'taskflowdi2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrdcdvOw2CgVDAqcuW0EkAu0kkxWzmjA',
    appId: '1:481479762043:ios:73b04b0c42bea350a502de',
    messagingSenderId: '481479762043',
    projectId: 'taskflowdi2',
    storageBucket: 'taskflowdi2.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrdcdvOw2CgVDAqcuW0EkAu0kkxWzmjA',
    appId: '1:481479762043:ios:5794af279f2d5e60a502de',
    messagingSenderId: '481479762043',
    projectId: 'taskflowdi2',
    storageBucket: 'taskflowdi2.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ24O4bVBqexlDXD8IN3ATmeSHvMxBCHI',
    appId: '1:481479762043:web:19c208b3efa44c70a502de',
    messagingSenderId: '481479762043',
    projectId: 'taskflowdi2',
    authDomain: 'taskflowdi2.firebaseapp.com',
    storageBucket: 'taskflowdi2.firebasestorage.app',
  );
}